create table if not exists public.goods (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name varchar not null,
  code integer not null,
  weight real not null check (weight > 0),
  price real not null check (price >= 0),
  has_paid boolean not null default false
);

create index if not exists idx_goods_code on public.goods (code);
create index if not exists idx_goods_created_at on public.goods (created_at desc);

alter table public.goods enable row level security;
