-- Aliya Cargo: customers + goods with soft delete
-- Full recreate (only if starting fresh). Prefer 20260724000000_soft_delete.sql for existing DBs.

drop table if exists public.goods cascade;
drop table if exists public.customers cascade;

create table public.customers (
  id bigint generated by default as identity primary key,
  phone text not null,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint customers_phone_digits check (phone ~ '^\d{9}$')
);

create unique index customers_phone_active_unique
  on public.customers (phone)
  where deleted_at is null;

create table public.goods (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers (id) on delete restrict,
  weight real not null check (weight > 0),
  price real not null check (price >= 0),
  has_paid boolean not null default false,
  initiator text,
  created_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_customers_phone on public.customers (phone);
create index if not exists idx_customers_name on public.customers (name);
create index if not exists idx_customers_deleted_at on public.customers (deleted_at);
create index if not exists idx_goods_customer_id on public.goods (customer_id);
create index if not exists idx_goods_created_at on public.goods (created_at desc);
create index if not exists idx_goods_has_paid on public.goods (has_paid);
create index if not exists idx_goods_deleted_at on public.goods (deleted_at);

alter table public.customers enable row level security;
alter table public.goods enable row level security;
