-- Aliya Cargo: customers + goods (phone instead of code)
-- Run this in Supabase → SQL Editor.
-- WARNING: this drops the old single-table goods schema.
-- Export/backup first if you need old test rows.

drop table if exists public.goods cascade;
drop table if exists public.customers cascade;

create table public.customers (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customers_phone_digits check (phone ~ '^\d{9}$')
);

create table public.goods (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers (id) on delete restrict,
  weight real not null check (weight > 0),
  price real not null check (price >= 0),
  has_paid boolean not null default false,
  initiator text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_customers_phone on public.customers (phone);
create index if not exists idx_customers_name on public.customers (name);
create index if not exists idx_goods_customer_id on public.goods (customer_id);
create index if not exists idx_goods_created_at on public.goods (created_at desc);
create index if not exists idx_goods_has_paid on public.goods (has_paid);

alter table public.customers enable row level security;
alter table public.goods enable row level security;
