-- Finance ledger: incomes and expenses (free-text notes)
-- Run in Supabase → SQL Editor

create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income', 'expense')),
  amount real not null check (amount > 0),
  note text not null check (char_length(trim(note)) > 0),
  created_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_finance_records_created_at
  on public.finance_records (created_at desc);

create index if not exists idx_finance_records_type
  on public.finance_records (type);

create index if not exists idx_finance_records_deleted_at
  on public.finance_records (deleted_at);

alter table public.finance_records enable row level security;
