-- Daily closing reports, generated automatically at local midnight (Asia/Dushanbe, UTC+5).
--
-- The database runs in UTC, so a business day D spans
--   [D 00:00+05, D+1 00:00+05) = [D-1 19:00Z, D 19:00Z)
-- and the cron entry fires at 19:00 UTC, which is 00:00 local of the following day.

create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.daily_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,

  -- Goods sorted during the day
  goods_count integer not null default 0,
  goods_weight real not null default 0,
  goods_revenue real not null default 0,

  -- Of those goods, what was already settled by midnight
  goods_paid_count integer not null default 0,
  goods_paid_revenue real not null default 0,

  -- Leftovers: goods sorted that day still unpaid at midnight
  unpaid_count integer not null default 0,
  unpaid_weight real not null default 0,
  unpaid_revenue real not null default 0,

  -- Cash actually collected during the day, including goods from earlier days
  payments_count integer not null default 0,
  payments_weight real not null default 0,
  payments_revenue real not null default 0,
  payments_by_collector jsonb not null default '[]'::jsonb,

  -- Finance ledger
  income_count integer not null default 0,
  income_total real not null default 0,
  expense_count integer not null default 0,
  expense_total real not null default 0,
  finance_items jsonb not null default '[]'::jsonb,

  -- Acceptances
  acceptances_count integer not null default 0,
  acceptance_weight real not null default 0,
  acceptance_cost real not null default 0,
  acceptances_closed integer not null default 0,
  waste_weight real not null default 0,

  new_clients_count integer not null default 0,

  -- Total outstanding debt across all clients as of midnight
  debt_count integer not null default 0,
  debt_weight real not null default 0,
  debt_revenue real not null default 0,
  debt_clients_count integer not null default 0,

  net_profit real not null default 0,

  generated_at timestamptz not null default now(),

  constraint daily_reports_report_date_unique unique (report_date)
);

create index if not exists idx_daily_reports_report_date
  on public.daily_reports (report_date desc);

alter table public.daily_reports enable row level security;

-- paid_at was added after some goods already existed, so fall back to created_at
-- when a row is flagged paid but carries no payment timestamp.
create or replace function public.generate_daily_report(target_date date default null)
returns public.daily_reports
language plpgsql
security definer
set search_path = public
as $fn$
declare
  tz constant text := 'Asia/Dushanbe';
  d date := coalesce(target_date, (timezone(tz, now()))::date - 1);
  day_start timestamptz := (d::timestamp) at time zone tz;
  day_end timestamptz := ((d + 1)::timestamp) at time zone tz;
  result public.daily_reports;
begin
  with sorted as (
    select
      count(*)::integer as cnt,
      coalesce(sum(weight), 0) as weight,
      coalesce(sum(price), 0) as revenue,
      count(*) filter (where has_paid and coalesce(paid_at, created_at) < day_end)::integer as paid_cnt,
      coalesce(sum(price) filter (where has_paid and coalesce(paid_at, created_at) < day_end), 0) as paid_revenue,
      count(*) filter (where not (has_paid and coalesce(paid_at, created_at) < day_end))::integer as unpaid_cnt,
      coalesce(sum(weight) filter (where not (has_paid and coalesce(paid_at, created_at) < day_end)), 0) as unpaid_weight,
      coalesce(sum(price) filter (where not (has_paid and coalesce(paid_at, created_at) < day_end)), 0) as unpaid_revenue
    from public.goods
    where deleted_at is null
      and created_at >= day_start
      and created_at < day_end
  ),
  payments as (
    select
      count(*)::integer as cnt,
      coalesce(sum(weight), 0) as weight,
      coalesce(sum(price), 0) as revenue
    from public.goods
    where deleted_at is null
      and has_paid
      and paid_at >= day_start
      and paid_at < day_end
  ),
  collectors as (
    select coalesce(
      jsonb_agg(
        jsonb_build_object('collector', collector, 'count', cnt, 'amount', amount)
        order by amount desc
      ),
      '[]'::jsonb
    ) as items
    from (
      select
        coalesce(nullif(payment_accepted_by, ''), '—') as collector,
        count(*)::integer as cnt,
        round(sum(price)::numeric, 2) as amount
      from public.goods
      where deleted_at is null
        and has_paid
        and paid_at >= day_start
        and paid_at < day_end
      group by 1
    ) t
  ),
  fin as (
    select
      count(*) filter (where type = 'income')::integer as income_cnt,
      coalesce(sum(amount) filter (where type = 'income'), 0) as income_total,
      count(*) filter (where type = 'expense')::integer as expense_cnt,
      coalesce(sum(amount) filter (where type = 'expense'), 0) as expense_total
    from public.finance_records
    where deleted_at is null
      and created_at >= day_start
      and created_at < day_end
  ),
  fin_items as (
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'type', type,
          'amount', round(amount::numeric, 2),
          'note', note,
          'created_by', created_by,
          'created_at', created_at
        )
        order by created_at
      ),
      '[]'::jsonb
    ) as items
    from public.finance_records
    where deleted_at is null
      and created_at >= day_start
      and created_at < day_end
  ),
  acc as (
    select
      count(*)::integer as cnt,
      coalesce(sum(total_weight), 0) as weight,
      coalesce(sum(paid_tjs), 0) as cost
    from public.acceptances
    where deleted_at is null
      and accepted_at = d
  ),
  acc_closed as (
    select
      count(*)::integer as cnt,
      coalesce(sum(waste_weight), 0) as waste
    from public.acceptances
    where deleted_at is null
      and closed_at >= day_start
      and closed_at < day_end
  ),
  cl as (
    select count(*)::integer as cnt
    from public.clients
    where deleted_at is null
      and created_at >= day_start
      and created_at < day_end
  ),
  debt as (
    select
      count(*)::integer as cnt,
      coalesce(sum(weight), 0) as weight,
      coalesce(sum(price), 0) as revenue,
      count(distinct client_id)::integer as clients
    from public.goods
    where deleted_at is null
      and created_at < day_end
      and not (has_paid and coalesce(paid_at, created_at) < day_end)
  )
  insert into public.daily_reports as r (
    report_date,
    goods_count, goods_weight, goods_revenue,
    goods_paid_count, goods_paid_revenue,
    unpaid_count, unpaid_weight, unpaid_revenue,
    payments_count, payments_weight, payments_revenue, payments_by_collector,
    income_count, income_total, expense_count, expense_total, finance_items,
    acceptances_count, acceptance_weight, acceptance_cost, acceptances_closed, waste_weight,
    new_clients_count,
    debt_count, debt_weight, debt_revenue, debt_clients_count,
    net_profit,
    generated_at
  )
  select
    d,
    sorted.cnt,
    round(sorted.weight::numeric, 3),
    round(sorted.revenue::numeric, 2),
    sorted.paid_cnt,
    round(sorted.paid_revenue::numeric, 2),
    sorted.unpaid_cnt,
    round(sorted.unpaid_weight::numeric, 3),
    round(sorted.unpaid_revenue::numeric, 2),
    payments.cnt,
    round(payments.weight::numeric, 3),
    round(payments.revenue::numeric, 2),
    collectors.items,
    fin.income_cnt,
    round(fin.income_total::numeric, 2),
    fin.expense_cnt,
    round(fin.expense_total::numeric, 2),
    fin_items.items,
    acc.cnt,
    round(acc.weight::numeric, 3),
    round(acc.cost::numeric, 2),
    acc_closed.cnt,
    round(acc_closed.waste::numeric, 3),
    cl.cnt,
    debt.cnt,
    round(debt.weight::numeric, 3),
    round(debt.revenue::numeric, 2),
    debt.clients,
    round((payments.revenue + fin.income_total - acc.cost - fin.expense_total)::numeric, 2),
    now()
  from sorted, payments, collectors, fin, fin_items, acc, acc_closed, cl, debt
  on conflict (report_date) do update set
    goods_count = excluded.goods_count,
    goods_weight = excluded.goods_weight,
    goods_revenue = excluded.goods_revenue,
    goods_paid_count = excluded.goods_paid_count,
    goods_paid_revenue = excluded.goods_paid_revenue,
    unpaid_count = excluded.unpaid_count,
    unpaid_weight = excluded.unpaid_weight,
    unpaid_revenue = excluded.unpaid_revenue,
    payments_count = excluded.payments_count,
    payments_weight = excluded.payments_weight,
    payments_revenue = excluded.payments_revenue,
    payments_by_collector = excluded.payments_by_collector,
    income_count = excluded.income_count,
    income_total = excluded.income_total,
    expense_count = excluded.expense_count,
    expense_total = excluded.expense_total,
    finance_items = excluded.finance_items,
    acceptances_count = excluded.acceptances_count,
    acceptance_weight = excluded.acceptance_weight,
    acceptance_cost = excluded.acceptance_cost,
    acceptances_closed = excluded.acceptances_closed,
    waste_weight = excluded.waste_weight,
    new_clients_count = excluded.new_clients_count,
    debt_count = excluded.debt_count,
    debt_weight = excluded.debt_weight,
    debt_revenue = excluded.debt_revenue,
    debt_clients_count = excluded.debt_clients_count,
    net_profit = excluded.net_profit,
    generated_at = excluded.generated_at
  returning r.* into result;

  return result;
end;
$fn$;

revoke all on function public.generate_daily_report(date) from public;
revoke all on function public.generate_daily_report(date) from anon, authenticated;
grant execute on function public.generate_daily_report(date) to service_role;

-- 19:00 UTC = 00:00 Asia/Dushanbe of the next day, so the report covers the day that just ended.
do $cron$
begin
  if exists (select 1 from cron.job where jobname = 'generate-daily-report') then
    perform cron.unschedule('generate-daily-report');
  end if;
  perform cron.schedule('generate-daily-report', '0 19 * * *', 'select public.generate_daily_report()');
exception
  when undefined_table then
    -- pg_cron catalog not ready; reports can still be generated via /api/reports
    null;
  when others then
    raise notice 'pg_cron schedule skipped: %', sqlerrm;
end;
$cron$;

-- Stamp new acceptances with the local date, otherwise batches entered between
-- 00:00 and 05:00 local land in the previous day's report.
alter table public.acceptances
  alter column accepted_at set default (timezone('Asia/Dushanbe', now()))::date;

-- Backfill every day that already has data so the report list is not empty.
do $backfill$
declare
  day date;
begin
  for day in
    select distinct day_value from (
      select (timezone('Asia/Dushanbe', created_at))::date as day_value from public.goods
      union select (timezone('Asia/Dushanbe', paid_at))::date from public.goods where paid_at is not null
      union select (timezone('Asia/Dushanbe', created_at))::date from public.finance_records
      union select (timezone('Asia/Dushanbe', created_at))::date from public.clients
      union select accepted_at from public.acceptances
    ) days
    where day_value is not null
    order by day_value
  loop
    perform public.generate_daily_report(day);
  end loop;
end;
$backfill$;
