-- Greenfield restart: wipe legacy schema and create the v1 domain
-- clients / acceptances / goods / finance_records

drop table if exists public.cargo_boxes cascade;
drop table if exists public.cargo_batches cascade;
drop table if exists public.reports cascade;
drop table if exists public.finance_records cascade;
drop table if exists public.goods cascade;
drop table if exists public.customers cascade;
drop table if exists public.clients cascade;
drop table if exists public.acceptances cascade;

create table public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint clients_phone_digits check (phone ~ '^\d{9}$')
);

create unique index clients_phone_active_uidx
  on public.clients (phone)
  where deleted_at is null;

create index clients_deleted_at_idx
  on public.clients (deleted_at);

create table public.acceptances (
  id bigint generated by default as identity primary key,
  accepted_at date not null default (timezone('utc', now())::date),
  total_weight real not null check (total_weight > 0),
  paid_tjs real not null check (paid_tjs >= 0),
  cost_per_kg real not null check (cost_per_kg >= 0),
  status text not null default 'open' check (status in ('open', 'closed')),
  closed_at timestamptz,
  waste_weight real check (waste_weight is null or waste_weight >= 0),
  created_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index acceptances_one_open_uidx
  on public.acceptances (status)
  where status = 'open' and deleted_at is null;

create index acceptances_accepted_at_idx
  on public.acceptances (accepted_at desc);

create index acceptances_status_idx
  on public.acceptances (status)
  where deleted_at is null;

create table public.goods (
  id bigint generated by default as identity primary key,
  acceptance_id bigint not null references public.acceptances (id) on delete restrict,
  client_id bigint not null references public.clients (id) on delete restrict,
  name text not null default '',
  weight real not null check (weight > 0),
  price real not null check (price >= 0),
  has_paid boolean not null default false,
  paid_at timestamptz,
  payment_accepted_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index goods_acceptance_id_idx
  on public.goods (acceptance_id)
  where deleted_at is null;

create index goods_client_id_idx
  on public.goods (client_id)
  where deleted_at is null;

create index goods_has_paid_idx
  on public.goods (has_paid)
  where deleted_at is null;

create index goods_created_at_idx
  on public.goods (created_at desc);

create table public.finance_records (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('income', 'expense')),
  amount real not null check (amount > 0),
  note text not null,
  created_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index finance_records_created_at_idx
  on public.finance_records (created_at desc);

create index finance_records_type_idx
  on public.finance_records (type)
  where deleted_at is null;

alter table public.clients enable row level security;
alter table public.acceptances enable row level security;
alter table public.goods enable row level security;
alter table public.finance_records enable row level security;
