-- Daily closing reports (immutable after insert)
-- Run in Supabase → SQL Editor

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  price_per_kg real not null check (price_per_kg >= 0),
  cost_per_kg real not null check (cost_per_kg >= 0),

  -- Today's warehouse activity
  goods_count integer not null default 0 check (goods_count >= 0),
  total_weight real not null default 0 check (total_weight >= 0),
  paid_count integer not null default 0 check (paid_count >= 0),
  paid_weight real not null default 0 check (paid_weight >= 0),
  paid_revenue real not null default 0 check (paid_revenue >= 0),

  -- Leftovers (unpaid packages from today)
  unpaid_count integer not null default 0 check (unpaid_count >= 0),
  unpaid_weight real not null default 0 check (unpaid_weight >= 0),
  unpaid_revenue real not null default 0 check (unpaid_revenue >= 0),

  -- Today's finance ledger
  other_income real not null default 0 check (other_income >= 0),
  other_expense real not null default 0 check (other_expense >= 0),

  -- Snapshot totals (frozen at create)
  cargo_cost real not null default 0,
  cargo_margin real not null default 0,
  income_total real not null default 0,
  expense_total real not null default 0,
  net_profit real not null default 0,

  note text not null default '',
  created_by text,
  created_at timestamptz not null default now(),

  constraint reports_report_date_unique unique (report_date)
);

create index if not exists idx_reports_report_date
  on public.reports (report_date desc);

create index if not exists idx_reports_created_at
  on public.reports (created_at desc);

alter table public.reports enable row level security;
