-- Cargo acceptance + sorting boxes (additive; does not touch existing rows)
-- Run in Supabase → SQL Editor

create table if not exists public.cargo_batches (
  id bigint generated by default as identity primary key,
  accepted_at date not null default (timezone('utc', now())::date),
  total_weight real not null check (total_weight > 0),
  cost_per_kg real not null check (cost_per_kg >= 0),
  total_cost real not null check (total_cost >= 0),
  note text not null default '',
  status text not null default 'open' check (status in ('open', 'closed')),
  created_by text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_cargo_batches_accepted_at
  on public.cargo_batches (accepted_at desc);

create index if not exists idx_cargo_batches_status
  on public.cargo_batches (status)
  where deleted_at is null;

create index if not exists idx_cargo_batches_deleted_at
  on public.cargo_batches (deleted_at);

create table if not exists public.cargo_boxes (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.cargo_batches (id) on delete restrict,
  label text not null default '',
  gross_weight real not null check (gross_weight > 0),
  tare_weight real check (tare_weight is null or (tare_weight >= 0 and tare_weight < gross_weight)),
  status text not null default 'pending' check (status in ('pending', 'sorted')),
  note text not null default '',
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_cargo_boxes_batch_id
  on public.cargo_boxes (batch_id);

create index if not exists idx_cargo_boxes_deleted_at
  on public.cargo_boxes (deleted_at);

alter table public.goods
  add column if not exists batch_id bigint references public.cargo_batches (id) on delete set null;

create index if not exists idx_goods_batch_id
  on public.goods (batch_id)
  where deleted_at is null;

alter table public.cargo_batches enable row level security;
alter table public.cargo_boxes enable row level security;
